export const ASSETS = {
  warrior: "assets/dawngeon/player-warrior.png",
  mage: "assets/dawngeon/player-mage.png",
  ranger: "assets/dawngeon/player-ranger-dark.svg",
  monster: "assets/dawngeon/monster-slime-dark.svg",
  monsterRat: "assets/dawngeon/monster-rat-dark.svg",
  monsterBat: "assets/dawngeon/monster-bat-dark.svg",
  monsterWolf: "assets/dawngeon/monster-wolf-dark.svg",
  elite: "assets/dawngeon/elite-dark.svg",
  boss: "assets/dawngeon/boss-dark.svg",
  chest: "assets/dawngeon/chest.png",
  altar: "assets/dawngeon/altar-dark.svg",
  forge: "assets/dawngeon/forge-dark.svg",
  shop: "assets/dawngeon/merchant-dark.svg",
  questNpc: "assets/dawngeon/quest-npc-dark.svg",
  fenceGate: "assets/dawngeon/fence-gate-dark.svg",
  trap: "assets/dawngeon/trap-spikes-dark.svg",
  portal: "assets/dawngeon/portal-dark.svg",
  stairsDown: "assets/dawngeon/stairs-down-dark.svg",
  stairsUp: "assets/dawngeon/stairs-up-dark.svg",
  floor: "assets/dawngeon/floor-dark.svg",
  wall: "assets/dawngeon/wall-dark.svg"
};
