export const QUEST_DEFS = {
  rescueRoom: {
    id: "rescueRoom",
    giver: "questNpc",
    title: "房间救援",
    giverName: "救援斥候卡尔",
    desc: "清理指定房间的怪物，救出被困的冒险者。",
    target: 2,
    rewardGold: (floor: number) => 18 + floor * 4,
    rewardKeys: 1,
    type: "rescueRoom"
  },
  wardenErrand: {
    id: "wardenErrand",
    giver: "questNpc",
    title: "巡夜人委托",
    giverName: "巡夜人罗恩",
    desc: "清掉本层游荡怪物，换取打开符文锁的钥匙。",
    target: 2,
    rewardGold: (floor: number) => 14 + floor * 3,
    rewardKeys: 1
  },
  eliteBounty: {
    id: "eliteBounty",
    giver: "questNpc",
    title: "精英悬赏",
    giverName: "悬赏官罗恩",
    desc: "追猎本层更危险的精英怪，削弱地牢对巡夜人的反扑。",
    target: 1,
    targetKind: "elite",
    rewardGold: (floor: number) => 18 + floor * 4,
    rewardKeys: 1,
    rewardSkillDust: 1,
    relation: "wardens"
  },
  roomPurge: {
    id: "roomPurge",
    giver: "questNpc",
    title: "房间净化",
    giverName: "记录员缇雅",
    desc: "清理指定房间里的怪物，回收房间门楣上异常跳动的符文残响。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardSkillDust: 2,
    rewardRune: true,
    relation: "runebound"
  },
  lockedRoomKey: {
    id: "lockedRoomKey",
    giver: "questNpc",
    title: "房门钥匙委托",
    giverName: "钥匙保管人诺维",
    desc: "清理附近游荡怪物，换取指定房间的钥匙。",
    target: 2,
    rewardGold: (floor: number) => 8 + floor * 2,
    rewardDoorKey: true
  },
  runeSurvey: {
    id: "runeSurvey",
    giver: "questNpc",
    title: "符文测绘",
    giverName: "测绘员缇雅",
    desc: "清理被符文回声干扰的区域，记录地牢回路的变化。",
    target: 1,
    rewardGold: (floor: number) => 9 + floor * 2,
    rewardSkillPoints: 1,
    rewardSkillDust: 2,
    rewardSkillScroll: true,
    relation: "runebound"
  },
  wardenSeal: {
    id: "wardenSeal",
    giver: "questNpc",
    title: "封印巡检",
    giverName: "封印官赛拉",
    desc: "检查本层松动的符文封印，清掉被封印气息引来的守卫。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardKeys: 1,
    rewardSkillPoints: 1,
    relation: "wardens"
  },
  wardenRelay: {
    id: "wardenRelay",
    giver: "questNpc",
    title: "巡夜接力",
    giverName: "传令员赛拉",
    desc: "把前哨路线打通。完成后会提高巡夜人对你的长期信任，并引出更深层封印委托。",
    target: 2,
    rewardGold: (floor: number) => 16 + floor * 3,
    rewardKeys: 1,
    rewardSkillPoints: 1,
    relation: "wardens",
    chainFlag: "wardenRelay"
  },
  survivorTrace: {
    id: "survivorTrace",
    giver: "questNpc",
    title: "幸存者暗记",
    giverName: "暗记记录员伊芙",
    desc: "沿着墙面暗记清理追踪者，让后续幸存者能辨认安全路线。",
    target: 2,
    rewardGold: (floor: number) => 11 + floor * 2,
    rewardPotion: "hp",
    rewardSkillPoints: 1,
    rewardSkillScroll: true,
    relation: "survivors"
  },
  survivorEscort: {
    id: "survivorEscort",
    giver: "questNpc",
    title: "撤离掩护",
    giverName: "领路人伊芙",
    desc: "清掉通往撤离暗记的追踪者。完成后幸存者会在后续事件中留下更多可用线索。",
    target: 2,
    rewardGold: (floor: number) => 13 + floor * 2,
    rewardPotion: "hp",
    rewardBeacon: true,
    relation: "survivors",
    chainFlag: "survivorEscort"
  },
  runeCalibration: {
    id: "runeCalibration",
    giver: "questNpc",
    title: "符文校准",
    giverName: "校准师缇雅",
    desc: "击败携带符文回声的目标，校准装备上的符文槽回路。",
    target: 2,
    targetKind: "runic",
    rewardGold: (floor: number) => 8 + floor * 2,
    rewardSkillDust: 3,
    rewardRune: true,
    relation: "runebound",
    chainFlag: "runeCalibration"
  },
  merchantRoute: {
    id: "merchantRoute",
    giver: "shop",
    title: "商路清理",
    giverName: "商队管事玛拉",
    desc: "帮商人扫清附近怪物，换取补给和金币。",
    target: 2,
    rewardGold: (floor: number) => 10 + floor * 3,
    rewardPotion: "hp"
  },
  merchantCache: {
    id: "merchantCache",
    giver: "shop",
    title: "补给回收",
    giverName: "商队管事玛拉",
    desc: "清掉占据补给箱附近的怪物，商队会给你更实用的远行工具。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardPotion: "mp",
    rewardBeacon: true,
    relation: "merchants",
    chainFlag: "merchantCache"
  }
} as const;
