export const QUEST_DEFS = {
  rescueRoom: {
    id: "rescueRoom",
    giver: "questNpc",
    title: "房间救援",
    giverName: "救援斥候卡尔",
    desc: "清理指定房间的怪物，确认被困者安全，并把幸存者接上撤离暗记。",
    target: 2,
    rewardGold: (floor: number) => 18 + floor * 4,
    rewardKeys: 1,
    type: "rescueRoom"
  },
  wardenErrand: {
    id: "wardenErrand",
    giver: "questNpc",
    title: "巡夜人委托",
    giverName: "巡夜人罗恩",
    desc: "夺回熄灯路段，让罗恩的巡夜灯号重新接向深层封印。",
    target: 2,
    rewardGold: (floor: number) => 14 + floor * 3,
    rewardKeys: 1
  },
  eliteBounty: {
    id: "eliteBounty",
    giver: "questNpc",
    title: "精英悬赏",
    giverName: "悬赏官罗恩",
    desc: "追猎沿巡夜界线活动的精英怪，替封印巡检争取时间。",
    target: 1,
    targetKind: "elite",
    rewardGold: (floor: number) => 18 + floor * 4,
    rewardKeys: 1,
    rewardSkillDust: 1,
    relation: "wardens"
  },
  roomPurge: {
    id: "roomPurge",
    giver: "questNpc",
    title: "房间净化",
    giverName: "记录员缇雅",
    desc: "清理异常房间，回收门楣残响，稳定测绘和撤离路线。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardSkillDust: 2,
    rewardRune: true,
    relation: "runebound"
  },
  lockedRoomKey: {
    id: "lockedRoomKey",
    giver: "questNpc",
    title: "房门钥匙委托",
    giverName: "钥匙保管人诺维",
    desc: "压住门外威胁，换取指定房间的专用符文钥匙。",
    target: 2,
    rewardGold: (floor: number) => 8 + floor * 2,
    rewardDoorKey: true
  },
  runeSurvey: {
    id: "runeSurvey",
    giver: "questNpc",
    title: "符文测绘",
    giverName: "测绘员缇雅",
    desc: "清理回声干扰源，重绘会被地牢改写的真实回路。",
    target: 1,
    rewardGold: (floor: number) => 9 + floor * 2,
    rewardSkillPoints: 1,
    rewardSkillDust: 2,
    rewardSkillScroll: true,
    relation: "runebound"
  },
  wardenSeal: {
    id: "wardenSeal",
    giver: "questNpc",
    title: "封印巡检",
    giverName: "封印官赛拉",
    desc: "巡检松动封条，清掉被封印裂隙引来的守卫。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardKeys: 1,
    rewardSkillPoints: 1,
    relation: "wardens"
  },
  wardenRelay: {
    id: "wardenRelay",
    giver: "questNpc",
    title: "巡夜接力",
    giverName: "传令员赛拉",
    desc: "打通前哨接力，把救援名单、灯号和测绘图送往深层。",
    target: 2,
    rewardGold: (floor: number) => 16 + floor * 3,
    rewardKeys: 1,
    rewardSkillPoints: 1,
    relation: "wardens",
    chainFlag: "wardenRelay"
  },
  survivorTrace: {
    id: "survivorTrace",
    giver: "questNpc",
    title: "幸存者暗记",
    giverName: "暗记记录员伊芙",
    desc: "沿墙面暗记清理追踪者，让被救出的人找到撤离线。",
    target: 2,
    rewardGold: (floor: number) => 11 + floor * 2,
    rewardPotion: "hp",
    rewardSkillPoints: 1,
    rewardSkillScroll: true,
    relation: "survivors"
  },
  survivorEscort: {
    id: "survivorEscort",
    giver: "questNpc",
    title: "撤离掩护",
    giverName: "领路人伊芙",
    desc: "守住被怪物嗅到的撤离暗记，替后续幸存者争取改路时间。",
    target: 2,
    rewardGold: (floor: number) => 13 + floor * 2,
    rewardPotion: "hp",
    rewardBeacon: true,
    relation: "survivors",
    chainFlag: "survivorEscort"
  },
  runeCalibration: {
    id: "runeCalibration",
    giver: "questNpc",
    title: "符文校准",
    giverName: "校准师缇雅",
    desc: "击败携带符文回声的目标，用战斗残留校准符文槽。",
    target: 2,
    targetKind: "runic",
    rewardGold: (floor: number) => 8 + floor * 2,
    rewardSkillDust: 3,
    rewardRune: true,
    relation: "runebound",
    chainFlag: "runeCalibration"
  },
  merchantRoute: {
    id: "merchantRoute",
    giver: "shop",
    title: "商路清理",
    giverName: "商队管事玛拉",
    desc: "扫清短程商路，让药水、信标和钥匙能靠近安全线。",
    target: 2,
    rewardGold: (floor: number) => 10 + floor * 3,
    rewardPotion: "hp"
  },
  merchantCache: {
    id: "merchantCache",
    giver: "shop",
    title: "补给回收",
    giverName: "商队管事玛拉",
    desc: "夺回深层补给箱，恢复信标、法力补给和撤离物资。",
    target: 2,
    rewardGold: (floor: number) => 12 + floor * 3,
    rewardPotion: "mp",
    rewardBeacon: true,
    relation: "merchants",
    chainFlag: "merchantCache"
  }
} as const;
